server:
  port: 4551

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.darts.stub.services.controllers
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/darts/"
  application:
    name: Darts Stub Services

wiremock:
  server:
    host: 127.0.0.1
    mappings-path: ${WIREMOCK_SERVER_MAPPINGS_PATH:wiremock}

azure:
  application-insights:
    instrumentation-key: ${darts.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

logging:
  level:
    root: DEBUG
